// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"github.com/rema424/sqlxx"
	"go-appengine-clean-architecture/internal/app/default/controller"
	"go-appengine-clean-architecture/internal/pkg/food"
)

// Injectors from wire.go:

func InitializeControllers(acsr *sqlxx.Accessor) *controller.Controller {
	repository := food.NewGateway(acsr)
	interactor := food.NewInteractor(repository)
	foodController := controller.NewFoodController(interactor)
	controllerController := controller.NewController(foodController)
	return controllerController
}
